//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace movies_project {
	
	
	public partial class Casts {
		
		protected System.Web.UI.WebControls.Content FeaturedContent;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl cast;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl crew;
	}
}
