//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace movies_project {
	
	
	public partial class Site {
		
		protected System.Web.UI.WebControls.ContentPlaceHolder head;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox search;
		
		protected System.Web.UI.WebControls.Button search_btn;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1;
	}
}
